// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXGjMhpuyqqit1YacN8J1R_3Ol5K8U8nc',
    appId: '1:4800903752:android:6504dd82b4b89b66ffb67d',
    messagingSenderId: '4800903752',
    projectId: 'unite-c9161',
    storageBucket: 'unite-c9161.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTlkaOKV-ZYdr5ntuCVgNW_roIxujr4QM',
    appId: '1:4800903752:ios:162eddbb5309c3bbffb67d',
    messagingSenderId: '4800903752',
    projectId: 'unite-c9161',
    storageBucket: 'unite-c9161.firebasestorage.app',
    iosBundleId: 'com.example.unite',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnfPDjDaRsK3QVTk5mSqC-QFzDg5CdbSE',
    appId: '1:4800903752:web:189899bf9a875a76ffb67d',
    messagingSenderId: '4800903752',
    projectId: 'unite-c9161',
    authDomain: 'unite-c9161.firebaseapp.com',
    storageBucket: 'unite-c9161.firebasestorage.app',
    measurementId: 'G-ESLF9N3Z3C',
  );
}
